apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.16
          ports:
            - containerPort: 9200
              name: http-rest
            - containerPort: 9300
              name: tcp
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/lib/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        storageClassName: "longhorn-storage"  # Longhorn 스토리지 사용
        accessModes: [ "ReadWriteOnce" ]  # RWO 모드
        resources:
          requests:
            storage: 5Gi